name: Test Build for PR

on:
  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm install
          npx webpack
          npm install -g less mocha
          lessc --source-map ./src/style.less dist/style.css
          ts-mocha src/scripts/test/*test.ts