name: Build and Deploy

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    strategy:
      matrix:
#        node-version: [ 14.x, 16.x, 18.x ]
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack
          npm install -g less
          lessc --source-map ./src/style.less dist/style.css
  #      - name: Deploy to Github Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          publish_dir: ./dist # Replace 'dist' with the directory where your build output resides
#          publish_branch: gh-pages
#          enable_jekyll: false

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2